### ISSUE TITLE
refactor? updateJob should return Job not array

### ISSUE THREAD

**Issue by MiroCillik** [keboola/job-queue-internal-api-php-client#18]
postJobResult also. And this method could be renamed, because it's not doing "POST" request. So either `putJobResult` or `setJobResult`?

Or the most correct would be to rename both methods:
`putJobStatus` and `putJobResult` or `set*` or `update*` :)

**Comment by odinuv** [comment]
https://keboola.atlassian.net/browse/PS-1682
